apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "name" . }}
  labels:
    {{ toYaml .Values.template.selectorLabels | indent 4 | trim }}
    chart: {{ template "chart" .}}
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.template.selectorLabels | indent 6 | trim }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.template.selectorLabels | indent 8 | trim }}
        chart: {{ template "chart" .}}
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: {{ template "name" . }}
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 3
      containers:
      - name: zebra
        image: {{ required "A valid .Values.image.repository entry required!" .Values.image.repository }}:{{ default "latest" .Values.image.tag }}
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        command:
        - entrypoint.sh
        - zebra
        ports:
        - name: http
          containerPort: 2601
        securityContext:
          privileged: True
        env:
        - name: NAME
          value: {{ template "name" . }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: var-run-quagga
          mountPath: "/var/run/quagga"
          readOnly: false
        - name: config
          mountPath: "/etc/quagga/zebra.conf"
          subPath: zebra.conf
      - name: bgpd
        image: {{ required "A valid .Values.image.repository entry required!" .Values.image.repository }}:{{ default "latest" .Values.image.tag }}
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        command:
        - entrypoint.sh
        - bgpd
        ports:
        - name: http
          containerPort: 2605
        securityContext:
          privileged: True
        env:
        - name: NAME
          value: {{ template "name" . }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: var-run-quagga
          mountPath: "/var/run/quagga"
          readOnly: false
        - name: config
          mountPath: "/etc/quagga/bgpd.conf"
          subPath: bgpd.conf
      - name: quagga
        image: {{ required "A valid .Values.image.repository entry required!" .Values.image.repository }}:{{ default "latest" .Values.image.tag }}
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        command:
        - entrypoint.sh
        - quagga
        securityContext:
          privileged: True
        env:
        - name: NAME
          value: {{ template "name" . }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: var-run-quagga
          mountPath: "/var/run/quagga"
          readOnly: false
      volumes:
      - name: var-run-quagga
        emptyDir:
          medium: Memory
      - name: config
        configMap:
          name: {{ template "name" . }}
          items:
          - key: zebra.conf
            path: zebra.conf
          - key: bgpd.conf
            path: bgpd.conf
