apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ toYaml .Values.template.selectorLabels | indent 4 | trim }}
    chart: {{ template "chart" .}}
